spring:
  datasource:
    url: jdbc:mysql://192.168.72.128:3306/test
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: MySql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
